import type { NextPage } from 'next'
import Head from 'next/head'
import {Canvas} from '@react-three/fiber';
import {Sky} from '@react-three/drei';

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Canvas>
				<Sky sunPosition={[100,100,20]} />
			</Canvas>
    </div>
  )
}

export default Home
